## Исследование надёжности заёмщиков

Заказчик — кредитный отдел банка. Нужно разобраться, влияет ли семейное положение и количество детей клиента на факт погашения кредита в срок. Входные данные от банка — статистика о платёжеспособности клиентов.

Результаты исследования будут учтены при построении модели **кредитного скоринга** — специальной системы, которая оценивает способность потенциального заёмщика вернуть кредит банку.

### Шаг 1. Откройте файл с данными и изучите общую информацию.

In [2]:
import pandas as pd
data = pd.read_csv('data.csv')

In [7]:
data.head(5)

,children,days_employed,dob_years,education,education_id,family_status,family_status_id,gender,income_type,debt,total_income,purpose
0,1,-8437.673028,42,высшее,0,женат / замужем,0,F,сотрудник,0,253875.639453,покупка жилья
1,1,-4024.803754,36,среднее,1,женат / замужем,0,F,сотрудник,0,112080.014102,приобретение автомобиля
2,0,-5623.422610,33,Среднее,1,женат / замужем,0,M,сотрудник,0,145885.952297,покупка жилья
3,3,-4124.747207,32,среднее,1,женат / замужем,0,M,сотрудник,0,267628.550329,дополнительное образование
4,0,340266.072047,53,среднее,1,гражданский брак,1,F,пенсионер,0,158616.077870,сыграть свадьбу

In [14]:
data.describe()

,children,days_employed,dob_years,education_id,family_status_id,debt,total_income
count,21525.000000,19351.000000,21525.000000,21525.000000,21525.000000,21525.000000,1.935100e+04
mean,0.538908,63046.497661,43.293380,0.817236,0.972544,0.080883,1.674223e+05
std,1.381587,140827.311974,12.574584,0.548138,1.420324,0.272661,1.029716e+05
min,-1.000000,-18388.949901,0.000000,0.000000,0.000000,0.000000,2.066726e+04
25%,0.000000,-2747.423625,33.000000,1.000000,0.000000,0.000000,1.030532e+05
50%,0.000000,-1203.369529,42.000000,1.000000,0.000000,0.000000,1.450179e+05
75%,1.000000,-291.095954,53.000000,1.000000,1.000000,0.000000,2.034351e+05
max,20.000000,401755.400475,75.000000,4.000000,4.000000,1.000000,2.265604e+06

In [16]:
data.family_status.value_counts()

женат / замужем          12380
гражданский брак          4177
Не женат / не замужем     2813
в разводе                 1195
вдовец / вдова             960
Name: family_status, dtype: int64

In [18]:
data.education.value_counts()

среднее                13750
высшее                  4718
СРЕДНЕЕ                  772
Среднее                  711
неоконченное высшее      668
ВЫСШЕЕ                   274
Высшее                   268
начальное                250
Неоконченное высшее       47
НЕОКОНЧЕННОЕ ВЫСШЕЕ       29
НАЧАЛЬНОЕ                 17
Начальное                 15
ученая степень             4
УЧЕНАЯ СТЕПЕНЬ             1
Ученая степень             1
Name: education, dtype: int64

### Вывод

### Шаг 2. Предобработка данных

### Обработка пропусков

In [28]:
for c in data.columns:
    print(f'{c} == {data[c].isna().sum()}')

children == 0
days_employed == 2174
dob_years == 0
education == 0
education_id == 0
family_status == 0
family_status_id == 0
gender == 0
income_type == 0
debt == 0
total_income == 2174
purpose == 0

In [29]:
data[data.isna().sum(axis=1)!=0]

,children,days_employed,dob_years,education,education_id,family_status,family_status_id,gender,income_type,debt,total_income,purpose
12,0,NaN,65,среднее,1,гражданский брак,1,M,пенсионер,0,NaN,сыграть свадьбу
26,0,NaN,41,среднее,1,женат / замужем,0,M,госслужащий,0,NaN,образование
29,0,NaN,63,среднее,1,Не женат / не замужем,4,F,пенсионер,0,NaN,строительство жилой недвижимости
41,0,NaN,50,среднее,1,женат / замужем,0,F,госслужащий,0,NaN,сделка с подержанным автомобилем
55,0,NaN,54,среднее,1,гражданский брак,1,F,пенсионер,1,NaN,сыграть свадьбу
65,0,NaN,21,среднее,1,Не женат / не замужем,4,M,компаньон,0,NaN,операции с коммерческой недвижимостью
67,0,NaN,52,высшее,0,женат / замужем,0,F,пенсионер,0,NaN,покупка жилья для семьи
72,1,NaN,32,высшее,0,женат / замужем,0,M,госслужащий,0,NaN,операции с коммерческой недвижимостью
82,2,NaN,50,высшее,0,женат / замужем,0,F,сотрудник,0,NaN,жилье
83,0,NaN,52,среднее,1,женат / замужем,0,M,сотрудник,0,NaN,жилье
90,2,NaN,35,высшее,0,женат / замужем,0,F,сотрудник,0,NaN,операции с жильем
94,1,NaN,34,высшее,0,гражданский брак,1,F,компаньон,0,NaN,на проведение свадьбы
96,0,NaN,44,СРЕДНЕЕ,1,женат / замужем,0,F,сотрудник,0,NaN,покупка жилой недвижимости
97,0,NaN,47,высшее,0,женат / замужем,0,F,сотрудник,0,NaN,профильное образование
120,0,NaN,46,среднее,1,женат / замужем,0,F,сотрудник,0,NaN,высшее образование
121,0,NaN,29,высшее,0,женат / замужем,0,F,компаньон,0,NaN,автомобиль
135,0,NaN,27,среднее,1,женат / замужем,0,M,компаньон,0,NaN,жилье
141,0,NaN,39,среднее,1,гражданский брак,1,M,сотрудник,0,NaN,свадьба
145,0,NaN,62,среднее,1,женат / замужем,0,M,пенсионер,0,NaN,строительство недвижимости
174,0,NaN,55,высшее,0,вдовец / вдова,2,F,компаньон,0,NaN,свой автомобиль
181,0,NaN,26,среднее,1,гражданский брак,1,F,компаньон,1,NaN,покупка жилья для семьи
189,1,NaN,30,среднее,1,Не женат / не замужем,4,F,сотрудник,0,NaN,свой автомобиль
205,1,NaN,31,высшее,0,женат / замужем,0,F,сотрудник,0,NaN,на покупку подержанного автомобиля
220,1,NaN,23,неоконченное высшее,2,гражданский брак,1,F,компаньон,0,NaN,сыграть свадьбу
241,0,NaN,47,среднее,1,женат / замужем,0,M,сотрудник,0,NaN,строительство собственной недвижимости
242,0,NaN,58,среднее,1,женат / замужем,0,F,госслужащий,0,NaN,покупка своего жилья
247,1,NaN,60,высшее,0,женат / замужем,0,F,пенсионер,1,NaN,заняться высшим образованием
250,0,NaN,54,высшее,0,женат / замужем,0,F,сотрудник,0,NaN,сделка с подержанным автомобилем
264,2,NaN,40,среднее,1,в разводе,3,F,сотрудник,0,NaN,недвижимость
278,1,NaN,23,Среднее,1,гражданский брак,1,F,сотрудник,1,NaN,автомобиль
...,...,...,...,...,...,...,...,...,...,...,...,...
21226,3,NaN,38,среднее,1,гражданский брак,1,M,сотрудник,0,NaN,получение образования
21242,1,NaN,33,высшее,0,Не женат / не замужем,4,F,госслужащий,0,NaN,строительство собственной недвижимости
21251,0,NaN,57,неоконченное высшее,2,гражданский брак,1,F,сотрудник,0,NaN,свадьба
21258,1,NaN,40,среднее,1,Не женат / не замужем,4,M,сотрудник,0,NaN,операции с жильем
21268,1,NaN,44,высшее,0,гражданский брак,1,F,госслужащий,0,NaN,на проведение свадьбы
21271,2,NaN,42,среднее,1,гражданский брак,1,M,сотрудник,1,NaN,операции со своей недвижимостью
21281,1,NaN,30,высшее,0,женат / замужем,0,F,сотрудник,0,NaN,покупка коммерческой недвижимости
21294,0,NaN,45,ВЫСШЕЕ,0,женат / замужем,0,F,сотрудник,0,NaN,высшее образование
21300,2,NaN,45,Среднее,1,гражданский брак,1,M,компаньон,0,NaN,получение дополнительного образования
21305,0,NaN,59,среднее,1,Не женат / не замужем,4,F,пенсионер,0,NaN,строительство собственной недвижимости
21308,0,NaN,48,среднее,1,женат / замужем,0,F,компаньон,0,NaN,покупка жилья для сдачи
21311,0,NaN,49,среднее,1,женат / замужем,0,F,пенсионер,0,NaN,покупка жилья для сдачи
21321,0,NaN,56,Среднее,1,женат / замужем,0,F,пенсионер,0,NaN,операции с недвижимостью
21350,0,NaN,21,среднее,1,Не женат / не замужем,4,M,компаньон,0,NaN,на покупку автомобиля
21364,0,NaN,50,среднее,1,женат / замужем,0,M,сотрудник,0,NaN,операции со своей недвижимостью
21369,2,NaN,42,среднее,1,в разводе,3,M,компаньон,0,NaN,покупка жилой недвижимости
21390,20,NaN,53,среднее,1,женат / замужем,0,M,компаньон,0,NaN,покупка жилой недвижимости
21391,0,NaN,52,среднее,1,женат / замужем,0,F,компаньон,0,NaN,покупка жилья для семьи
21407,1,NaN,36,среднее,1,женат / замужем,0,F,компаньон,0,NaN,строительство жилой недвижимости
21414,0,NaN,65,среднее,1,женат / замужем,0,F,пенсионер,0,NaN,покупка своего жилья
21415,0,NaN,54,среднее,1,женат / замужем,0,F,пенсионер,0,NaN,операции с жильем
21423,0,NaN,63,среднее,1,женат / замужем,0,M,пенсионер,0,NaN,сделка с автомобилем
21426,0,NaN,49,среднее,1,женат / замужем,0,F,сотрудник,1,NaN,недвижимость
21432,1,NaN,38,неоконченное высшее,2,Не женат / не замужем,4,F,сотрудник,0,NaN,операции с жильем
21463,1,NaN,35,высшее,0,гражданский брак,1,M,сотрудник,0,NaN,на проведение свадьбы
21489,2,NaN,47,Среднее,1,женат / замужем,0,M,компаньон,0,NaN,сделка с автомобилем
21495,1,NaN,50,среднее,1,гражданский брак,1,F,сотрудник,0,NaN,свадьба
21497,0,NaN,48,ВЫСШЕЕ,0,женат / замужем,0,F,компаньон,0,NaN,строительство недвижимости
21502,1,NaN,42,среднее,1,женат / замужем,0,F,сотрудник,0,NaN,строительство жилой недвижимости
21510,2,NaN,28,среднее,1,женат / замужем,0,F,сотрудник,0,NaN,приобретение автомобиля

In [30]:
data.fillna(method='pad')

,children,days_employed,dob_years,education,education_id,family_status,family_status_id,gender,income_type,debt,total_income,purpose
0,1,-8437.673028,42,высшее,0,женат / замужем,0,F,сотрудник,0,253875.639453,покупка жилья
1,1,-4024.803754,36,среднее,1,женат / замужем,0,F,сотрудник,0,112080.014102,приобретение автомобиля
2,0,-5623.422610,33,Среднее,1,женат / замужем,0,M,сотрудник,0,145885.952297,покупка жилья
3,3,-4124.747207,32,среднее,1,женат / замужем,0,M,сотрудник,0,267628.550329,дополнительное образование
4,0,340266.072047,53,среднее,1,гражданский брак,1,F,пенсионер,0,158616.077870,сыграть свадьбу
5,0,-926.185831,27,высшее,0,гражданский брак,1,M,компаньон,0,255763.565419,покупка жилья
6,0,-2879.202052,43,высшее,0,женат / замужем,0,F,компаньон,0,240525.971920,операции с жильем
7,0,-152.779569,50,СРЕДНЕЕ,1,женат / замужем,0,M,сотрудник,0,135823.934197,образование
8,2,-6929.865299,35,ВЫСШЕЕ,0,гражданский брак,1,F,сотрудник,0,95856.832424,на проведение свадьбы
9,0,-2188.756445,41,среднее,1,женат / замужем,0,M,сотрудник,0,144425.938277,покупка жилья для семьи
10,2,-4171.483647,36,высшее,0,женат / замужем,0,M,компаньон,0,113943.491460,покупка недвижимости
11,0,-792.701887,40,среднее,1,женат / замужем,0,F,сотрудник,0,77069.234271,покупка коммерческой недвижимости
12,0,-792.701887,65,среднее,1,гражданский брак,1,M,пенсионер,0,77069.234271,сыграть свадьбу
13,0,-1846.641941,54,неоконченное высшее,2,женат / замужем,0,F,сотрудник,0,130458.228857,приобретение автомобиля
14,0,-1844.956182,56,высшее,0,гражданский брак,1,F,компаньон,1,165127.911772,покупка жилой недвижимости
15,1,-972.364419,26,среднее,1,женат / замужем,0,F,сотрудник,0,116820.904450,строительство собственной недвижимости
16,0,-1719.934226,35,среднее,1,женат / замужем,0,F,сотрудник,0,289202.704229,недвижимость
17,0,-2369.999720,33,высшее,0,гражданский брак,1,M,сотрудник,0,90410.586745,строительство недвижимости
18,0,400281.136913,53,среднее,1,вдовец / вдова,2,F,пенсионер,0,56823.777243,на покупку подержанного автомобиля
19,0,-10038.818549,48,СРЕДНЕЕ,1,в разводе,3,F,сотрудник,0,242831.107982,на покупку своего автомобиля
20,1,-1311.604166,36,среднее,1,женат / замужем,0,M,сотрудник,0,209552.644578,недвижимость
21,1,-253.685166,33,среднее,1,гражданский брак,1,F,сотрудник,0,131812.203909,приобретение автомобиля
22,1,-1766.644138,24,среднее,1,гражданский брак,1,F,сотрудник,0,149681.140731,на покупку подержанного автомобиля
23,0,-272.981385,21,высшее,0,гражданский брак,1,M,сотрудник,0,128265.720871,сыграть свадьбу
24,1,338551.952911,57,среднее,1,Не женат / не замужем,4,F,пенсионер,0,290547.235997,операции с коммерческой недвижимостью
25,0,363548.489348,67,среднее,1,женат / замужем,0,M,пенсионер,0,55112.757732,покупка недвижимости
26,0,363548.489348,41,среднее,1,женат / замужем,0,M,госслужащий,0,55112.757732,образование
27,0,-529.191635,28,высшее,0,женат / замужем,0,M,сотрудник,0,308848.983691,строительство собственной недвижимости
28,1,-717.274324,26,высшее,0,женат / замужем,0,F,сотрудник,0,187863.237306,строительство собственной недвижимости
29,0,-717.274324,63,среднее,1,Не женат / не замужем,4,F,пенсионер,0,187863.237306,строительство жилой недвижимости
...,...,...,...,...,...,...,...,...,...,...,...,...
21495,1,-960.095747,50,среднее,1,гражданский брак,1,F,сотрудник,0,176369.594491,свадьба
21496,1,-759.680851,31,среднее,1,женат / замужем,0,F,сотрудник,0,119392.620079,на покупку автомобиля
21497,0,-759.680851,48,ВЫСШЕЕ,0,женат / замужем,0,F,компаньон,0,119392.620079,строительство недвижимости
21498,1,-1330.627998,32,среднее,1,гражданский брак,1,M,сотрудник,0,240767.575887,сыграть свадьбу
21499,0,-9929.015065,57,среднее,1,гражданский брак,1,M,компаньон,0,157553.158589,свадьба
21500,0,-578.082757,26,неоконченное высшее,2,Не женат / не замужем,4,M,компаньон,0,77813.293365,операции с коммерческой недвижимостью
21501,0,334343.096304,57,среднее,1,женат / замужем,0,F,пенсионер,0,86232.126549,жилье
21502,1,334343.096304,42,среднее,1,женат / замужем,0,F,сотрудник,0,86232.126549,строительство жилой недвижимости
21503,0,-3096.881131,58,среднее,1,женат / замужем,0,F,сотрудник,0,264250.997662,заняться образованием
21504,0,355235.728158,68,среднее,1,женат / замужем,0,F,пенсионер,0,80566.321329,дополнительное образование
21505,0,338904.866406,53,среднее,1,гражданский брак,1,M,пенсионер,0,75439.993167,сыграть свадьбу
21506,1,-1556.249906,33,ВЫСШЕЕ,0,гражданский брак,1,F,сотрудник,0,145541.993320,свадьба
21507,1,-79.832064,32,среднее,1,гражданский брак,1,F,госслужащий,0,98180.279152,сделка с подержанным автомобилем
21508,0,386497.714078,62,среднее,1,женат / замужем,0,M,пенсионер,0,72638.590915,недвижимость
21509,0,362161.054124,59,высшее,0,женат / замужем,0,M,пенсионер,0,73029.059379,операции с недвижимостью
21510,2,362161.054124,28,среднее,1,женат / замужем,0,F,сотрудник,0,73029.059379,приобретение автомобиля
21511,0,-612.569129,29,высшее,0,гражданский брак,1,F,сотрудник,1,140068.472941,покупка жилья для сдачи
21512,0,-165.377752,26,высшее,0,Не женат / не замужем,4,M,компаньон,0,147301.457769,получение дополнительного образования
21513,0,-1166.216789,35,среднее,1,женат / замужем,0,F,сотрудник,0,250986.142309,покупка жилья
21514,0,-280.469996,27,неоконченное высшее,2,Не женат / не замужем,4,M,компаньон,0,355988.407188,строительство недвижимости
21515,1,-467.685130,28,среднее,1,женат / замужем,0,F,сотрудник,1,109486.327999,заняться образованием
21516,0,-914.391429,42,высшее,0,женат / замужем,0,F,компаньон,0,322807.776603,покупка своего жилья
21517,0,-404.679034,42,высшее,0,гражданский брак,1,F,компаньон,0,178059.553491,на покупку своего автомобиля
21518,0,373995.710838,59,СРЕДНЕЕ,1,женат / замужем,0,F,пенсионер,0,153864.650328,сделка с автомобилем
21519,1,-2351.431934,37,ученая степень,4,в разводе,3,M,сотрудник,0,115949.039788,покупка коммерческой недвижимости
21520,1,-4529.316663,43,среднее,1,гражданский брак,1,F,компаньон,0,224791.862382,операции с жильем
21521,0,343937.404131,67,среднее,1,женат / замужем,0,F,пенсионер,0,155999.806512,сделка с автомобилем
21522,1,-2113.346888,38,среднее,1,гражданский брак,1,M,сотрудник,1,89672.561153,недвижимость
21523,3,-3112.481705,38,среднее,1,женат / замужем,0,M,сотрудник,1,244093.050500,на покупку своего автомобиля
21524,2,-1984.507589,40,среднее,1,женат / замужем,0,F,сотрудник,0,82047.418899,на покупку автомобиля

### Вывод

### Замена типа данных

### Вывод

### Обработка дубликатов

In [32]:
data.drop_duplicates()

,children,days_employed,dob_years,education,education_id,family_status,family_status_id,gender,income_type,debt,total_income,purpose
0,1,-8437.673028,42,высшее,0,женат / замужем,0,F,сотрудник,0,253875.639453,покупка жилья
1,1,-4024.803754,36,среднее,1,женат / замужем,0,F,сотрудник,0,112080.014102,приобретение автомобиля
2,0,-5623.422610,33,Среднее,1,женат / замужем,0,M,сотрудник,0,145885.952297,покупка жилья
3,3,-4124.747207,32,среднее,1,женат / замужем,0,M,сотрудник,0,267628.550329,дополнительное образование
4,0,340266.072047,53,среднее,1,гражданский брак,1,F,пенсионер,0,158616.077870,сыграть свадьбу
5,0,-926.185831,27,высшее,0,гражданский брак,1,M,компаньон,0,255763.565419,покупка жилья
6,0,-2879.202052,43,высшее,0,женат / замужем,0,F,компаньон,0,240525.971920,операции с жильем
7,0,-152.779569,50,СРЕДНЕЕ,1,женат / замужем,0,M,сотрудник,0,135823.934197,образование
8,2,-6929.865299,35,ВЫСШЕЕ,0,гражданский брак,1,F,сотрудник,0,95856.832424,на проведение свадьбы
9,0,-2188.756445,41,среднее,1,женат / замужем,0,M,сотрудник,0,144425.938277,покупка жилья для семьи
10,2,-4171.483647,36,высшее,0,женат / замужем,0,M,компаньон,0,113943.491460,покупка недвижимости
11,0,-792.701887,40,среднее,1,женат / замужем,0,F,сотрудник,0,77069.234271,покупка коммерческой недвижимости
12,0,NaN,65,среднее,1,гражданский брак,1,M,пенсионер,0,NaN,сыграть свадьбу
13,0,-1846.641941,54,неоконченное высшее,2,женат / замужем,0,F,сотрудник,0,130458.228857,приобретение автомобиля
14,0,-1844.956182,56,высшее,0,гражданский брак,1,F,компаньон,1,165127.911772,покупка жилой недвижимости
15,1,-972.364419,26,среднее,1,женат / замужем,0,F,сотрудник,0,116820.904450,строительство собственной недвижимости
16,0,-1719.934226,35,среднее,1,женат / замужем,0,F,сотрудник,0,289202.704229,недвижимость
17,0,-2369.999720,33,высшее,0,гражданский брак,1,M,сотрудник,0,90410.586745,строительство недвижимости
18,0,400281.136913,53,среднее,1,вдовец / вдова,2,F,пенсионер,0,56823.777243,на покупку подержанного автомобиля
19,0,-10038.818549,48,СРЕДНЕЕ,1,в разводе,3,F,сотрудник,0,242831.107982,на покупку своего автомобиля
20,1,-1311.604166,36,среднее,1,женат / замужем,0,M,сотрудник,0,209552.644578,недвижимость
21,1,-253.685166,33,среднее,1,гражданский брак,1,F,сотрудник,0,131812.203909,приобретение автомобиля
22,1,-1766.644138,24,среднее,1,гражданский брак,1,F,сотрудник,0,149681.140731,на покупку подержанного автомобиля
23,0,-272.981385,21,высшее,0,гражданский брак,1,M,сотрудник,0,128265.720871,сыграть свадьбу
24,1,338551.952911,57,среднее,1,Не женат / не замужем,4,F,пенсионер,0,290547.235997,операции с коммерческой недвижимостью
25,0,363548.489348,67,среднее,1,женат / замужем,0,M,пенсионер,0,55112.757732,покупка недвижимости
26,0,NaN,41,среднее,1,женат / замужем,0,M,госслужащий,0,NaN,образование
27,0,-529.191635,28,высшее,0,женат / замужем,0,M,сотрудник,0,308848.983691,строительство собственной недвижимости
28,1,-717.274324,26,высшее,0,женат / замужем,0,F,сотрудник,0,187863.237306,строительство собственной недвижимости
29,0,NaN,63,среднее,1,Не женат / не замужем,4,F,пенсионер,0,NaN,строительство жилой недвижимости
...,...,...,...,...,...,...,...,...,...,...,...,...
21495,1,NaN,50,среднее,1,гражданский брак,1,F,сотрудник,0,NaN,свадьба
21496,1,-759.680851,31,среднее,1,женат / замужем,0,F,сотрудник,0,119392.620079,на покупку автомобиля
21497,0,NaN,48,ВЫСШЕЕ,0,женат / замужем,0,F,компаньон,0,NaN,строительство недвижимости
21498,1,-1330.627998,32,среднее,1,гражданский брак,1,M,сотрудник,0,240767.575887,сыграть свадьбу
21499,0,-9929.015065,57,среднее,1,гражданский брак,1,M,компаньон,0,157553.158589,свадьба
21500,0,-578.082757,26,неоконченное высшее,2,Не женат / не замужем,4,M,компаньон,0,77813.293365,операции с коммерческой недвижимостью
21501,0,334343.096304,57,среднее,1,женат / замужем,0,F,пенсионер,0,86232.126549,жилье
21502,1,NaN,42,среднее,1,женат / замужем,0,F,сотрудник,0,NaN,строительство жилой недвижимости
21503,0,-3096.881131,58,среднее,1,женат / замужем,0,F,сотрудник,0,264250.997662,заняться образованием
21504,0,355235.728158,68,среднее,1,женат / замужем,0,F,пенсионер,0,80566.321329,дополнительное образование
21505,0,338904.866406,53,среднее,1,гражданский брак,1,M,пенсионер,0,75439.993167,сыграть свадьбу
21506,1,-1556.249906,33,ВЫСШЕЕ,0,гражданский брак,1,F,сотрудник,0,145541.993320,свадьба
21507,1,-79.832064,32,среднее,1,гражданский брак,1,F,госслужащий,0,98180.279152,сделка с подержанным автомобилем
21508,0,386497.714078,62,среднее,1,женат / замужем,0,M,пенсионер,0,72638.590915,недвижимость
21509,0,362161.054124,59,высшее,0,женат / замужем,0,M,пенсионер,0,73029.059379,операции с недвижимостью
21510,2,NaN,28,среднее,1,женат / замужем,0,F,сотрудник,0,NaN,приобретение автомобиля
21511,0,-612.569129,29,высшее,0,гражданский брак,1,F,сотрудник,1,140068.472941,покупка жилья для сдачи
21512,0,-165.377752,26,высшее,0,Не женат / не замужем,4,M,компаньон,0,147301.457769,получение дополнительного образования
21513,0,-1166.216789,35,среднее,1,женат / замужем,0,F,сотрудник,0,250986.142309,покупка жилья
21514,0,-280.469996,27,неоконченное высшее,2,Не женат / не замужем,4,M,компаньон,0,355988.407188,строительство недвижимости
21515,1,-467.685130,28,среднее,1,женат / замужем,0,F,сотрудник,1,109486.327999,заняться образованием
21516,0,-914.391429,42,высшее,0,женат / замужем,0,F,компаньон,0,322807.776603,покупка своего жилья
21517,0,-404.679034,42,высшее,0,гражданский брак,1,F,компаньон,0,178059.553491,на покупку своего автомобиля
21518,0,373995.710838,59,СРЕДНЕЕ,1,женат / замужем,0,F,пенсионер,0,153864.650328,сделка с автомобилем
21519,1,-2351.431934,37,ученая степень,4,в разводе,3,M,сотрудник,0,115949.039788,покупка коммерческой недвижимости
21520,1,-4529.316663,43,среднее,1,гражданский брак,1,F,компаньон,0,224791.862382,операции с жильем
21521,0,343937.404131,67,среднее,1,женат / замужем,0,F,пенсионер,0,155999.806512,сделка с автомобилем
21522,1,-2113.346888,38,среднее,1,гражданский брак,1,M,сотрудник,1,89672.561153,недвижимость
21523,3,-3112.481705,38,среднее,1,женат / замужем,0,M,сотрудник,1,244093.050500,на покупку своего автомобиля
21524,2,-1984.507589,40,среднее,1,женат / замужем,0,F,сотрудник,0,82047.418899,на покупку автомобиля

### Вывод

### Лемматизация

In [35]:
data.groupby(by=["purpose"]).mean()

,children,days_employed,dob_years,education_id,family_status_id,debt,total_income
purpose,,,,,,,
автомобили,0.489540,68581.452358,43.853556,0.765690,1.092050,0.092050,170832.075102
автомобиль,0.454545,71437.562058,43.715152,0.802020,0.917172,0.084848,169537.311320
высшее образование,0.651214,61208.470504,43.026490,0.799117,0.938190,0.088300,172043.948982
дополнительное образование,0.649351,71215.649021,44.164502,0.824675,1.047619,0.082251,163811.309755
жилье,0.630603,61337.939201,42.346213,0.806801,1.032457,0.071097,168745.717486
заняться высшим образованием,0.516129,60353.486610,43.197581,0.840726,0.933468,0.086694,155166.261965
заняться образованием,0.509709,58525.553316,43.822816,0.813107,0.839806,0.094660,170736.496576
на покупку автомобиля,0.514831,69177.684784,43.387712,0.847458,0.989407,0.093220,174032.120959
на покупку подержанного автомобиля,0.705637,68292.724657,43.962422,0.816284,1.037578,0.075157,162910.979756
на покупку своего автомобиля,0.465347,54437.226944,42.681188,0.800000,0.936634,0.091089,165506.375276
на проведение свадьбы,0.583012,65202.723184,42.939511,0.787645,1.000000,0.082368,169858.691963
недвижимость,0.493691,56383.838445,42.954259,0.787066,1.015773,0.066246,168229.908593
образование,0.525727,64403.541760,42.968680,0.789709,1.002237,0.071588,164108.027102
операции с жильем,0.577335,59368.224464,43.208270,0.820827,1.007657,0.073507,176607.973633
операции с коммерческой недвижимостью,0.611367,64395.365086,42.875576,0.788018,0.924731,0.079877,169665.507057
операции с недвижимостью,0.482249,65252.848535,42.894970,0.816568,1.025148,0.081361,169190.947414
операции со своей недвижимостью,0.525397,61228.134552,44.134921,0.874603,0.955556,0.079365,163972.945679
покупка жилой недвижимости,0.538715,54652.467564,43.416804,0.802306,0.993410,0.067545,171584.370045
покупка жилья,0.567233,67183.594821,42.414219,0.820711,0.933539,0.074189,167816.524502
покупка жилья для сдачи,0.537519,62138.114145,42.629403,0.813170,0.903522,0.079632,166815.839642
покупка жилья для семьи,0.489860,66853.172635,44.279251,0.814353,0.936037,0.070203,166412.649441
покупка коммерческой недвижимости,0.560241,61509.312469,43.908133,0.814759,1.040663,0.070783,165958.724055
покупка недвижимости,0.512821,64837.478148,43.504808,0.802885,0.847756,0.068910,174084.272553
покупка своего жилья,0.506452,49589.438210,43.101613,0.787097,0.911290,0.054839,170993.349542
получение высшего образования,0.474178,60255.793024,43.244131,0.835681,0.969484,0.107981,166732.726649
получение дополнительного образования,0.521253,71986.745036,44.080537,0.823266,0.961969,0.114094,158001.608598
получение образования,0.564334,68149.065417,42.618510,0.848758,0.932280,0.083521,169655.487034
приобретение автомобиля,0.471861,64834.700552,43.376623,0.798701,1.019481,0.090909,165631.303105
профильное образование,0.513761,63798.159801,43.745413,0.876147,0.931193,0.100917,161119.016521
ремонт жилью,0.516340,59428.994629,42.601307,0.802288,0.993464,0.057190,172724.609304
свадьба,0.485571,58578.431334,43.412798,0.816813,1.000000,0.080301,161780.581664
свой автомобиль,0.618750,61131.842890,43.172917,0.858333,0.908333,0.100000,160490.036656
сделка с автомобилем,0.465934,63563.849362,42.881319,0.892308,1.024176,0.109890,166325.647002
сделка с подержанным автомобилем,0.613497,64622.284523,44.261759,0.809816,0.979550,0.104294,170446.988387
строительство жилой недвижимости,0.460064,68609.022262,43.161342,0.849840,1.038339,0.076677,167998.555357
строительство недвижимости,0.501613,60589.265026,43.572581,0.848387,0.911290,0.087097,164394.417165
строительство собственной недвижимости,0.634646,64832.092137,43.181102,0.812598,0.977953,0.066142,166656.054762
сыграть свадьбу,0.538760,65377.286536,43.316537,0.798450,1.000000,0.074935,165910.277583

### Вывод

### Категоризация данных

### Вывод

### Шаг 3. Ответьте на вопросы

- Есть ли зависимость между наличием детей и возвратом кредита в срок?

### Вывод

- Есть ли зависимость между семейным положением и возвратом кредита в срок?

### Вывод

- Есть ли зависимость между уровнем дохода и возвратом кредита в срок?

### Вывод

- Как разные цели кредита влияют на его возврат в срок?

### Вывод

### Шаг 4. Общий вывод

### Чек-лист готовности проекта

Поставьте 'x' в выполненных пунктах. Далее нажмите Shift+Enter.

- [x]  открыт файл;
- [ ]  файл изучен;
- [ ]  определены пропущенные значения;
- [ ]  заполнены пропущенные значения;
- [ ]  есть пояснение, какие пропущенные значения обнаружены;
- [ ]  описаны возможные причины появления пропусков в данных;
- [ ]  объяснено, по какому принципу заполнены пропуски;
- [ ]  заменен вещественный тип данных на целочисленный;
- [ ]  есть пояснение, какой метод используется для изменения типа данных и почему;
- [ ]  удалены дубликаты;
- [ ]  есть пояснение, какой метод используется для поиска и удаления дубликатов;
- [ ]  описаны возможные причины появления дубликатов в данных;
- [ ]  выделены леммы в значениях столбца с целями получения кредита;
- [ ]  описан процесс лемматизации;
- [ ]  данные категоризированы;
- [ ]  есть объяснение принципа категоризации данных;
- [ ]  есть ответ на вопрос: "Есть ли зависимость между наличием детей и возвратом кредита в срок?";
- [ ]  есть ответ на вопрос: "Есть ли зависимость между семейным положением и возвратом кредита в срок?";
- [ ]  есть ответ на вопрос: "Есть ли зависимость между уровнем дохода и возвратом кредита в срок?";
- [ ]  есть ответ на вопрос: "Как разные цели кредита влияют на его возврат в срок?";
- [ ]  в каждом этапе есть выводы;
- [ ]  есть общий вывод.